web:
  build: web
  environment:
    - RACK_ENV=development
  ports:
    - 3000:3000
  volumes:
    - web:/app
    - web/conf/nginx.conf:/etc/nginx/nginx.conf
  links:
    - postgres
    - redis
worker:
  build: worker
  environment:
    - RACK_ENV=development
  volumes:
    - worker:/app
  links:
    - postgres
    - redis
redis:
  image: convox/redis
postgres:
  image: convox/postgres
