web: &web
  build: .
  command: bin/web
  environment:
    - RACK_ENV=development
    - POSTGRES_URL=postgres://postgres:password@postgres:5432/app
    - REDIS_URL=redis://redis:password@redis:6379/0
  ports:
    - 3000:3000
  volumes:
    - .:/app
  links:
    - postgres
    - redis
worker:
  <<: *web
  ports: []
redis:
  image: convox/redis
postgres:
  image: convox/postgres
