web:
  build: .
  command: bin/web
  environment:
    - RACK_ENV=development
  ports:
    - 3000:3000
  volumes:
    - .:/app
  links:
    - postgres
    - redis
worker:
  build: .
  command: bin/worker
  environment:
    - RACK_ENV=development
  volumes:
    - .:/app
  links:
    - postgres
    - redis
redis:
  image: convox/redis
postgres:
  image: convox/postgres
